### ISSUE TITLE
目录下的文件内容为空

### ISSUE THREAD

**Issue by J1ezds** [SexyBeast233/SecDictionary#2]
我git clone项目后，发现以下两个文件是空的
./硬件设备默认口令/Huawei华为.txt
./filelak/H5-Server中间件.txt

**Comment by SexyBeast233** [comment]
这两个字典原来在计划中想单独拿出来来着 , 最近时间请有点多, 就没去准备整理细化字典 , 为空是正常的

**Comment by SexyBeast233** [comment]
先解决硬件设备口令字典 , H5-Server中间件这个考虑删除 , 使用次数不高 , 也没有积累 ,缺乏实战意义

**Comment by SexyBeast233** [comment]
中间件字典使用频率还是低 ， 取消该字典计划 ， 推荐使用api接口加参数关键字字典和三四字符字典交替使用
